#define SCREEN_OFFSET 10
#define SCREEN_TITLE "Tetris"
#define SCREEN_WIDTH 500
#define SCREEN_HEIGHT 620
#define GAME_SPEED 60
#define TETROMINO_CELL_SIZE 30
#define CELL_SEPERATOR_SIZE 1
#define NUMBER_OF_CELL_IN_A_ROW 10
#define NUMBER_OF_ROW_IN_WINDOW 20
#define TETROMINO_MOVING_DELAY 0.2
#define GAME_WINDOW_OFF_SET 10
#define TETROMINO_X_OFFSET ((SCREEN_WIDTH / 2))
#define TETROMINO_Y_OFFSET SCREEN_OFFSET
#define BOUNDARY_PIXEL '#'
#define EMPTY_PIXEL ' '
#define BLOCK_PIXEX 'o'
