#define SCREEN_OFFSET 10
#define SCREEN_WIDTH (80 + SCREEN_OFFSET)
#define SCREEN_HEIGHT (30 + SCREEN_OFFSET)
#define TETROMINO_X_OFFSET (SCREEN_WIDTH / 2)
#define TETROMINO_Y_OFFSET SCREEN_OFFSET
#define BOUNDARY_PIXEL '#'
#define EMPTY_PIXEL ' '
#define BLOCK_PIXEX 'o'
