#define SCREEN_OFFSET 10
#define SCREEN_TITLE "Tetris"
#define SCREEN_WIDTH 300
#define SCREEN_HEIGHT 600
#define GAME_SPEED 60
#define TETROMINO_X_OFFSET ((SCREEN_WIDTH / 2))
#define TETROMINO_Y_OFFSET SCREEN_OFFSET
#define BOUNDARY_PIXEL '#'
#define EMPTY_PIXEL ' '
#define BLOCK_PIXEX 'o'
